#!/bin/bash
# Builds MangoDisplayRoku.zip ready for sideloading (manifest must sit at
# the zip root, which is why this zips the contents, not the folder).
#
#   ./package.sh          # TEST build (the default - safe)
#   ./package.sh prod     # PRODUCTION build; requires PROD_API_VERSION
#                         # (e.g. PROD_API_VERSION=v1.0.5 ./package.sh prod)
#
# The environment is compiled in via source/env.brs, regenerated here per
# build. The checked-in env.brs is always the TEST one; a prod build
# restores it afterwards so the working tree never silently carries prod.
set -euo pipefail
cd "$(dirname "$0")"

ENV="${1:-test}"

write_test_env() {
cat > source/env.brs <<'EOF'
' GENERATED by package.sh - the checked-in copy is the TEST environment,
' so a naive build can never accidentally target production. For a prod
' channel run ./package.sh prod (which requires PROD_API_VERSION and
' regenerates this file for the duration of the build).
'
' Codes registered on one backend can only be claimed from the matching
' webapp, and the control endpoint must serve the same environment the
' device paired against.
function envConfig() as object
    return {
        name: "test"
        apiBase: "https://testapi.mangomirror.com/v1.0.5/"
        setupHost: "testapp.mangodisplay.com"
        controlBase: "https://roku-control-test.mangodisplay.com"
    }
end function
EOF
}

case "$ENV" in
  test)
    write_test_env
    ;;
  prod)
    # The device-facing API version is a deliberate decision (prod webapp
    # is on v1.0.16 while Tizen and the portal's prod block use v1.0.5) -
    # refuse to guess it.
    : "${PROD_API_VERSION:?set PROD_API_VERSION (e.g. v1.0.5) for a prod build}"
    trap write_test_env EXIT
cat > source/env.brs <<EOF
' GENERATED by package.sh - PRODUCTION build. Do not commit this version;
' the checked-in env.brs is the test one (package.sh restores it).
function envConfig() as object
    return {
        name: "production"
        apiBase: "https://api.mangomirror.com/${PROD_API_VERSION}/"
        setupHost: "app.mangodisplay.com"
        controlBase: "https://roku-control.mangodisplay.com"
    }
end function
EOF
    ;;
  *)
    echo "usage: ./package.sh [test|prod]" >&2
    exit 1
    ;;
esac

rm -f MangoDisplayRoku.zip
zip -r MangoDisplayRoku.zip manifest source components images fonts media -x '*.DS_Store'
echo ""
echo "Created MangoDisplayRoku.zip  (environment: $ENV)"
echo "Install via browser at http://ROKU_TV_IP (Application Installer), or:"
echo "  curl -u rokudev:YOUR_DEV_PASSWORD --digest -F 'mysubmit=Install' -F 'archive=@MangoDisplayRoku.zip' http://ROKU_TV_IP/plugin_install"
