#!/bin/bash
# Fetch the portal's Google Fonts catalog as TTFs for bundling in the
# Roku channel, and generate the family->file map the overlays compile in.
#
# The single source of truth is the portal's own <link> to
# fonts.googleapis.com in index.html - whatever families the portal
# offers, this bundles (regular weight only, per Dave 2026-08-24: no
# bold, no italics). A family added to the portal later simply falls
# back to Source Sans Pro on the TV until this script reruns and the
# channel ships again.
#
# TTF trick: fonts.googleapis.com serves woff2 to browsers but plain
# TTF urls to clients whose User-Agent predates woff2 - curl's own UA
# does the job. Roku renders TTF/OTF only.
set -u
PORTAL_INDEX="${1:-$HOME/Projects/Mangomirror-Portal/WebContent/index.html}"
REPO="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO/fonts/gf"
MAP="$REPO/source/fontMap.brs"
# the tvOS app reads the same catalog as JSON (family -> path under
# fonts/); both maps are emitted from the same loop so the two clients
# can never disagree about which file a family resolves to
JSON_MAP="$REPO/tvos/MangoDisplayTV/fontMap.json"
mkdir -p "$OUT"

# families from the google fonts href: family=Name+With+Plus
families=$(grep -o 'family=[A-Za-z+]*' "$PORTAL_INDEX" | sed 's/^family=//; s/+/ /g' | sort -u | grep -v "Material Icons")

ok=0; fail=0; entries=""; json_entries=""
while IFS= read -r fam; do
    [ -z "$fam" ] && continue
    [ "$fam" = "Source Sans Pro" ] && continue  # already bundled as the fallback
    enc=$(printf '%s' "$fam" | sed 's/ /+/g')
    safe=$(printf '%s' "$fam" | tr -cd 'A-Za-z0-9')
    css=$(curl -s --max-time 20 -A "curl/7.79.1" "https://fonts.googleapis.com/css2?family=${enc}&display=swap")
    url=$(printf '%s' "$css" | grep -o 'https://fonts.gstatic.com/[^)]*\.ttf' | head -1)
    if [ -z "$url" ]; then
        echo "FAIL  $fam (no ttf url)"
        fail=$((fail+1))
        continue
    fi
    if curl -s --max-time 30 -o "$OUT/$safe.ttf" "$url" && [ -s "$OUT/$safe.ttf" ]; then
        echo "ok    $fam -> fonts/gf/$safe.ttf ($(du -k "$OUT/$safe.ttf" | cut -f1)KB)"
        ok=$((ok+1))
        entries="$entries        \"$fam\": \"pkg:/fonts/gf/$safe.ttf\"
"
        json_entries="$json_entries  \"$fam\": \"gf/$safe.ttf\",
"
    else
        echo "FAIL  $fam (download)"
        fail=$((fail+1))
    fi
done <<< "$families"

cat > "$MAP" << EOF
' GENERATED by tools/fetch-roku-fonts.sh - do not edit by hand.
' Maps the portal's Google Fonts families (regular weight) to the TTFs
' bundled under fonts/gf/. Unknown families return "" and the caller
' falls back to Source Sans Pro.
function rokuFontFile(family as dynamic) as string
    if family = invalid then return ""
    m = {
$entries    }
    f = m[family]
    if f <> invalid then return f
    return ""
end function
EOF

printf '{\n%s}\n' "${json_entries%,
}
" > "$JSON_MAP"

echo "----"
echo "$ok fonts bundled, $fail failed; maps written to source/fontMap.brs + tvos/MangoDisplayTV/fontMap.json"
du -sh "$OUT"
