' GENERATED by tools/generate-celebrations.js - do not edit by hand.
function celebrationBurstMeta() as object
    return { uri: "pkg:/images/celebrations/burst.png", frameW: 409, frameH: 409, frameCount: 24, cols: 5, rows: 5, frameMs: 70 }
end function
