' GENERATED by package.sh - the checked-in copy is the TEST environment,
' so a naive build can never accidentally target production. For a prod
' channel run ./package.sh prod (which requires PROD_API_VERSION and
' regenerates this file for the duration of the build).
'
' Codes registered on one backend can only be claimed from the matching
' webapp, and the control endpoint must serve the same environment the
' device paired against.
function envConfig() as object
    return {
        name: "test"
        apiBase: "https://testapi.mangomirror.com/v1.0.5/"
        setupHost: "testapp.mangodisplay.com"
        controlBase: "https://roku-control-test.mangodisplay.com"
    }
end function
