' GENERATED by tools/fetch-roku-fonts.sh - do not edit by hand.
' Maps the portal's Google Fonts families (regular weight) to their files
' under fonts/gf/ in the repo. The files are NOT bundled in the channel
' (8.5MB of fonts blew Roku's 4MB package limit, 2026-09-03): the service
' publishes them next to the display assets and FontTask fetches the few a
' display's manifest names into cachefs before its pages are applied.
' Unknown families return "" and the caller falls back to Source Sans Pro.
function rokuFontFile(family as dynamic) as string
    if family = invalid then return ""
    m = {
        "Abril Fatface": "gf/AbrilFatface.ttf"
        "Alfa Slab One": "gf/AlfaSlabOne.ttf"
        "Amatic SC": "gf/AmaticSC.ttf"
        "Arvo": "gf/Arvo.ttf"
        "Bad Script": "gf/BadScript.ttf"
        "Bebas Neue": "gf/BebasNeue.ttf"
        "Cabin": "gf/Cabin.ttf"
        "Cabin Sketch": "gf/CabinSketch.ttf"
        "Caudex": "gf/Caudex.ttf"
        "Caveat": "gf/Caveat.ttf"
        "Charm": "gf/Charm.ttf"
        "Cinzel Decorative": "gf/CinzelDecorative.ttf"
        "Comfortaa": "gf/Comfortaa.ttf"
        "Covered By Your Grace": "gf/CoveredByYourGrace.ttf"
        "DM Sans": "gf/DMSans.ttf"
        "Dancing Script": "gf/DancingScript.ttf"
        "Federo": "gf/Federo.ttf"
        "Fira Sans": "gf/FiraSans.ttf"
        "Great Vibes": "gf/GreatVibes.ttf"
        "IBM Plex Mono": "gf/IBMPlexMono.ttf"
        "Inconsolata": "gf/Inconsolata.ttf"
        "Indie Flower": "gf/IndieFlower.ttf"
        "Italiana": "gf/Italiana.ttf"
        "Josefin Sans": "gf/JosefinSans.ttf"
        "Kalam": "gf/Kalam.ttf"
        "Kaushan Script": "gf/KaushanScript.ttf"
        "Krona One": "gf/KronaOne.ttf"
        "Lato": "gf/Lato.ttf"
        "Libre Baskerville": "gf/LibreBaskerville.ttf"
        "Lobster": "gf/Lobster.ttf"
        "Lora": "gf/Lora.ttf"
        "Merienda": "gf/Merienda.ttf"
        "Merriweather": "gf/Merriweather.ttf"
        "Montserrat": "gf/Montserrat.ttf"
        "Muli": "gf/Muli.ttf"
        "Nunito": "gf/Nunito.ttf"
        "Nunito Sans": "gf/NunitoSans.ttf"
        "Open Sans": "gf/OpenSans.ttf"
        "PT Serif": "gf/PTSerif.ttf"
        "Pacifico": "gf/Pacifico.ttf"
        "Permanent Marker": "gf/PermanentMarker.ttf"
        "Petit Formal Script": "gf/PetitFormalScript.ttf"
        "Playfair Display": "gf/PlayfairDisplay.ttf"
        "Poppins": "gf/Poppins.ttf"
        "Quicksand": "gf/Quicksand.ttf"
        "Raleway": "gf/Raleway.ttf"
        "Roboto": "gf/Roboto.ttf"
        "Roboto Mono": "gf/RobotoMono.ttf"
        "Roboto Slab": "gf/RobotoSlab.ttf"
        "Satisfy": "gf/Satisfy.ttf"
        "Shadows Into Light": "gf/ShadowsIntoLight.ttf"
        "Source Code Pro": "gf/SourceCodePro.ttf"
        "Space Grotesk": "gf/SpaceGrotesk.ttf"
        "Space Mono": "gf/SpaceMono.ttf"
        "Syne": "gf/Syne.ttf"
        "Titillium Web": "gf/TitilliumWeb.ttf"
        "Ubuntu": "gf/Ubuntu.ttf"
        "Viaoda Libre": "gf/ViaodaLibre.ttf"
        "Whisper": "gf/Whisper.ttf"
        "Work Sans": "gf/WorkSans.ttf"
    }
    f = m[family]
    if f <> invalid then return f
    return ""
end function

' The on-device file for a family: the copy FontTask fetched into cachefs,
' or "" when it is not there (unknown family, download failed, cache
' evicted) - callers fall back to the bundled Source Sans Pro. One flat
' name per file: cachefs keeps no directories worth relying on.
function rokuFontCachePath(file as string) as string
    return "cachefs:/mmfont_" + file.Replace("/", "_")
end function

' Render-thread safe: roFileSystem is a MAIN/TASK-only component (creating
' it in a SceneGraph component crashed the scene at first paint,
' 2026-09-03), so the set of fonts known to be in cachefs lives on the
' global node - FontTask checks and fetches, MainScene records the result
' in m.global.fontsReady, everyone else just looks it up.
function rokuFontPath(family as dynamic) as string
    f = rokuFontFile(family)
    if f = "" then return ""
    have = m.global.fontsReady
    if have = invalid or have[f] <> true then return ""
    return rokuFontCachePath(f)
end function
